name: composer-installers-extender

services:
  php:
    type: php:7.4
    via: cli
    xdebug: true

tooling:
  composer:
    service: php
    description: Run composer commands
    cmd: composer
  php:
    service: php
  phpunit:
    service: php
    cmd: vendor/bin/phpunit
  phpcs:
    service: php
    cmd: vendor/bin/phpcs
