name: Test
on: [ push ]

jobs:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - uses: php-actions/phpunit@v1
      with:
        config: phpunit.xml

